In [2]:
from animegetter import AnimeDataManager

import pandas as pd
import numpy as np
import json
import networkx as nx
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('backupdata/anime_data.csv')

In [4]:
df.head(2)

,id,title,main_picture,alternative_titles,start_date,end_date,synopsis,mean,rank,popularity,num_list_users,num_scoring_users,genres,media_type,status,num_episodes
0,52991,Sousou no Frieren,"{""medium"": ""https://cdn.myanimelist.net/images...","{""synonyms"": [""Frieren at the Funeral"", ""Frier...",2023-09-29,2024-03-22,During their decade-long quest to defeat the D...,9.31,1,156,1065722,624327,"[{""id"": 2, ""name"": ""Adventure""}, {""id"": 8, ""na...",tv,finished_airing,28
1,5114,Fullmetal Alchemist: Brotherhood,"{""medium"": ""https://cdn.myanimelist.net/images...","{""synonyms"": [""Hagane no Renkinjutsushi: Fullm...",2009-04-05,2010-07-04,After a horrific alchemy experiment goes wrong...,9.10,2,3,3497034,2204122,"[{""id"": 1, ""name"": ""Action""}, {""id"": 2, ""name""...",tv,finished_airing,64

In [5]:
anime_ids = list(df['id'])

In [6]:
client_id = '5c3e3ceabcdf8331aa956557c1088152'
anime_manager = AnimeDataManager(client_id)

In [7]:
recommendations = anime_manager.get_anime_recommendations(anime_ids, use_mal=True)

Retrieving recommendations for 13898 anime from MAL API...

Fetching recommendations from MAL API:   1%|          | 147/13898 [02:01<4:40:50,  1.23s/it]

Error retrieving recommendations for anime 30276: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/30276?fields=recommendations

Fetching recommendations from MAL API:   1%|          | 148/13898 [03:32<107:12:07, 28.07s/it]

Error retrieving recommendations for anime 40834: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/40834?fields=recommendations

Fetching recommendations from MAL API:   1%|          | 149/13898 [05:03<178:57:11, 46.86s/it]

Error retrieving recommendations for anime 60988: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/60988?fields=recommendations

Fetching recommendations from MAL API:   2%|▏         | 304/13898 [08:40<3:20:52,  1.13it/s]

Error retrieving recommendations for anime 45: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/45?fields=recommendations

Fetching recommendations from MAL API:   2%|▏         | 305/13898 [10:11<105:05:20, 27.83s/it]

Error retrieving recommendations for anime 36371: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/36371?fields=recommendations

Fetching recommendations from MAL API:   2%|▏         | 306/13898 [11:42<176:20:24, 46.71s/it]

Error retrieving recommendations for anime 9735: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/9735?fields=recommendations

Fetching recommendations from MAL API:   3%|▎         | 462/13898 [15:20<4:07:51,  1.11s/it]

Error retrieving recommendations for anime 40852: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/40852?fields=recommendations

Fetching recommendations from MAL API:   3%|▎         | 463/13898 [16:51<104:19:20, 27.95s/it]

Error retrieving recommendations for anime 25537: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/25537?fields=recommendations

Fetching recommendations from MAL API:   3%|▎         | 464/13898 [18:21<174:27:27, 46.75s/it]

Error retrieving recommendations for anime 54856: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/54856?fields=recommendations

Fetching recommendations from MAL API:   5%|▍         | 636/13898 [22:10<2:31:00,  1.46it/s]

Error retrieving recommendations for anime 42640: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/42640?fields=recommendations

Fetching recommendations from MAL API:   5%|▍         | 637/13898 [23:41<101:51:33, 27.65s/it]

Error retrieving recommendations for anime 33161: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/33161?fields=recommendations

Fetching recommendations from MAL API:   5%|▍         | 638/13898 [25:12<171:32:11, 46.57s/it]

Error retrieving recommendations for anime 39783: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/39783?fields=recommendations

Fetching recommendations from MAL API:   6%|▌         | 804/13898 [29:00<3:15:01,  1.12it/s]

Error retrieving recommendations for anime 73: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/73?fields=recommendations

Fetching recommendations from MAL API:   6%|▌         | 805/13898 [30:31<101:11:39, 27.82s/it]

Error retrieving recommendations for anime 187: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/187?fields=recommendations

Fetching recommendations from MAL API:   6%|▌         | 806/13898 [32:02<169:40:56, 46.66s/it]

Error retrieving recommendations for anime 53199: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/53199?fields=recommendations

Fetching recommendations from MAL API:   7%|▋         | 962/13898 [35:40<4:03:32,  1.13s/it]

Error retrieving recommendations for anime 14175: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/14175?fields=recommendations

Fetching recommendations from MAL API:   7%|▋         | 963/13898 [37:11<100:29:14, 27.97s/it]

Error retrieving recommendations for anime 39534: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/39534?fields=recommendations

Fetching recommendations from MAL API:   7%|▋         | 964/13898 [38:42<168:10:40, 46.81s/it]

Error retrieving recommendations for anime 48926: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/48926?fields=recommendations

Fetching recommendations from MAL API:   8%|▊         | 1135/13898 [42:30<2:26:02,  1.46it/s]

Error retrieving recommendations for anime 38333: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/38333?fields=recommendations

Fetching recommendations from MAL API:   8%|▊         | 1136/13898 [44:01<98:04:52, 27.67s/it]

Error retrieving recommendations for anime 1824: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/1824?fields=recommendations

Fetching recommendations from MAL API:   8%|▊         | 1137/13898 [45:32<165:03:29, 46.56s/it]

Error retrieving recommendations for anime 35678: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/35678?fields=recommendations

Fetching recommendations from MAL API:   9%|▉         | 1294/13898 [49:10<2:25:14,  1.45it/s]

Error retrieving recommendations for anime 2724: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2724?fields=recommendations

Fetching recommendations from MAL API:   9%|▉         | 1295/13898 [50:41<96:49:08, 27.66s/it]

Error retrieving recommendations for anime 27633: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/27633?fields=recommendations

Fetching recommendations from MAL API:   9%|▉         | 1296/13898 [52:12<162:54:36, 46.54s/it]

Error retrieving recommendations for anime 25303: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/25303?fields=recommendations

Fetching recommendations from MAL API:  10%|█         | 1453/13898 [55:50<2:18:12,  1.50it/s]

Error retrieving recommendations for anime 42423: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/42423?fields=recommendations

Fetching recommendations from MAL API:  10%|█         | 1454/13898 [57:21<95:37:29, 27.66s/it]

Error retrieving recommendations for anime 2665: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2665?fields=recommendations

Fetching recommendations from MAL API:  10%|█         | 1455/13898 [58:52<161:01:03, 46.59s/it]

Error retrieving recommendations for anime 2673: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2673?fields=recommendations

Fetching recommendations from MAL API:  12%|█▏        | 1612/13898 [1:02:30<2:21:07,  1.45it/s]

Error retrieving recommendations for anime 821: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/821?fields=recommendations

Fetching recommendations from MAL API:  12%|█▏        | 1613/13898 [1:04:01<94:27:44, 27.68s/it]

Error retrieving recommendations for anime 12725: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/12725?fields=recommendations

Fetching recommendations from MAL API:  12%|█▏        | 1614/13898 [1:05:31<158:56:45, 46.58s/it]

Error retrieving recommendations for anime 25649: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/25649?fields=recommendations

Fetching recommendations from MAL API:  13%|█▎        | 1780/13898 [1:09:20<5:19:54,  1.58s/it]

Error retrieving recommendations for anime 48438: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/48438?fields=recommendations

Fetching recommendations from MAL API:  13%|█▎        | 1781/13898 [1:10:51<95:17:07, 28.31s/it]

Error retrieving recommendations for anime 3001: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/3001?fields=recommendations

Fetching recommendations from MAL API:  13%|█▎        | 1782/13898 [1:12:22<158:15:24, 47.02s/it]

Error retrieving recommendations for anime 52080: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/52080?fields=recommendations

Fetching recommendations from MAL API:  14%|█▍        | 1939/13898 [1:15:57<2:13:35,  1.49it/s]

Error retrieving recommendations for anime 41120: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/41120?fields=recommendations

Fetching recommendations from MAL API:  14%|█▍        | 1940/13898 [1:17:31<94:52:05, 28.56s/it]

Error retrieving recommendations for anime 1251: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/1251?fields=recommendations

Fetching recommendations from MAL API:  14%|█▍        | 1941/13898 [1:19:02<156:46:21, 47.20s/it]

Error retrieving recommendations for anime 38710: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/38710?fields=recommendations

Fetching recommendations from MAL API:  15%|█▌        | 2086/13898 [1:22:30<2:34:20,  1.28it/s]

Error retrieving recommendations for anime 38659: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/38659?fields=recommendations

Fetching recommendations from MAL API:  15%|█▌        | 2087/13898 [1:24:01<91:00:03, 27.74s/it]

Error retrieving recommendations for anime 13267: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/13267?fields=recommendations

Fetching recommendations from MAL API:  15%|█▌        | 2088/13898 [1:25:31<152:57:34, 46.63s/it]

Error retrieving recommendations for anime 10378: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/10378?fields=recommendations

Fetching recommendations from MAL API:  16%|█▌        | 2244/13898 [1:29:10<2:51:05,  1.14it/s]

Error retrieving recommendations for anime 3392: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/3392?fields=recommendations

Fetching recommendations from MAL API:  16%|█▌        | 2245/13898 [1:30:41<89:57:21, 27.79s/it]

Error retrieving recommendations for anime 2171: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2171?fields=recommendations

Fetching recommendations from MAL API:  16%|█▌        | 2246/13898 [1:32:11<151:03:18, 46.67s/it]

Error retrieving recommendations for anime 49847: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/49847?fields=recommendations

Fetching recommendations from MAL API:  17%|█▋        | 2403/13898 [1:35:51<3:04:46,  1.04it/s]

Error retrieving recommendations for anime 48483: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/48483?fields=recommendations

Fetching recommendations from MAL API:  17%|█▋        | 2404/13898 [1:37:21<88:57:52, 27.86s/it]

Error retrieving recommendations for anime 14575: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/14575?fields=recommendations

Fetching recommendations from MAL API:  17%|█▋        | 2405/13898 [1:38:52<149:06:24, 46.71s/it]

Error retrieving recommendations for anime 10620: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/10620?fields=recommendations

Fetching recommendations from MAL API:  18%|█▊        | 2551/13898 [1:42:20<2:07:18,  1.49it/s]

Error retrieving recommendations for anime 42519: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/42519?fields=recommendations

Fetching recommendations from MAL API:  18%|█▊        | 2552/13898 [1:43:51<87:07:29, 27.64s/it]

Error retrieving recommendations for anime 35756: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/35756?fields=recommendations

Fetching recommendations from MAL API:  18%|█▊        | 2553/13898 [1:45:21<146:46:24, 46.57s/it]

Error retrieving recommendations for anime 2670: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2670?fields=recommendations

Fetching recommendations from MAL API:  20%|█▉        | 2720/13898 [1:49:10<4:55:08,  1.58s/it]

Error retrieving recommendations for anime 24655: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/24655?fields=recommendations

Fetching recommendations from MAL API:  20%|█▉        | 2721/13898 [1:50:41<87:50:22, 28.29s/it]

Error retrieving recommendations for anime 901: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/901?fields=recommendations

Fetching recommendations from MAL API:  20%|█▉        | 2722/13898 [1:52:12<145:54:11, 47.00s/it]

Error retrieving recommendations for anime 38360: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/38360?fields=recommendations

Fetching recommendations from MAL API:  21%|██        | 2904/13898 [1:56:10<2:41:40,  1.13it/s]

Error retrieving recommendations for anime 6381: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/6381?fields=recommendations

Fetching recommendations from MAL API:  21%|██        | 2905/13898 [1:57:41<84:51:57, 27.79s/it]

Error retrieving recommendations for anime 33004: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/33004?fields=recommendations

Fetching recommendations from MAL API:  21%|██        | 2906/13898 [1:59:11<142:25:50, 46.65s/it]

Error retrieving recommendations for anime 13333: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/13333?fields=recommendations

Fetching recommendations from MAL API:  22%|██▏       | 3063/13898 [2:02:50<2:55:19,  1.03it/s]

Error retrieving recommendations for anime 53873: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/53873?fields=recommendations

Fetching recommendations from MAL API:  22%|██▏       | 3064/13898 [2:04:21<83:53:22, 27.88s/it]

Error retrieving recommendations for anime 40881: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/40881?fields=recommendations

Fetching recommendations from MAL API:  22%|██▏       | 3065/13898 [2:05:51<140:35:19, 46.72s/it]

Error retrieving recommendations for anime 31919: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/31919?fields=recommendations

Fetching recommendations from MAL API:  23%|██▎       | 3222/13898 [2:09:30<3:20:39,  1.13s/it]

Error retrieving recommendations for anime 2361: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2361?fields=recommendations

Fetching recommendations from MAL API:  23%|██▎       | 3223/13898 [2:11:01<82:57:44, 27.98s/it]

Error retrieving recommendations for anime 49202: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/49202?fields=recommendations

Fetching recommendations from MAL API:  23%|██▎       | 3224/13898 [2:12:32<138:46:02, 46.80s/it]

Error retrieving recommendations for anime 24029: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/24029?fields=recommendations

Fetching recommendations from MAL API:  24%|██▍       | 3381/13898 [2:16:10<3:47:09,  1.30s/it]

Error retrieving recommendations for anime 48624: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/48624?fields=recommendations

Fetching recommendations from MAL API:  24%|██▍       | 3382/13898 [2:17:41<82:05:50, 28.10s/it]

Error retrieving recommendations for anime 1191: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/1191?fields=recommendations

Fetching recommendations from MAL API:  24%|██▍       | 3383/13898 [2:19:11<136:51:50, 46.86s/it]

Error retrieving recommendations for anime 3861: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/3861?fields=recommendations

Fetching recommendations from MAL API:  26%|██▌       | 3555/13898 [2:23:00<1:55:06,  1.50it/s]

Error retrieving recommendations for anime 43693: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/43693?fields=recommendations

Fetching recommendations from MAL API:  26%|██▌       | 3556/13898 [2:24:31<79:26:20, 27.65s/it]

Error retrieving recommendations for anime 2683: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2683?fields=recommendations

Fetching recommendations from MAL API:  26%|██▌       | 3557/13898 [2:26:02<133:47:13, 46.58s/it]

Error retrieving recommendations for anime 34604: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/34604?fields=recommendations

Fetching recommendations from MAL API:  27%|██▋       | 3713/13898 [2:29:40<1:54:15,  1.49it/s]

Error retrieving recommendations for anime 41456: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/41456?fields=recommendations

Fetching recommendations from MAL API:  27%|██▋       | 3714/13898 [2:31:11<78:18:40, 27.68s/it]

Error retrieving recommendations for anime 1531: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/1531?fields=recommendations

Fetching recommendations from MAL API:  27%|██▋       | 3715/13898 [2:32:41<131:43:45, 46.57s/it]

Error retrieving recommendations for anime 2117: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2117?fields=recommendations

Fetching recommendations from MAL API:  28%|██▊       | 3881/13898 [2:36:30<3:39:16,  1.31s/it]

Error retrieving recommendations for anime 49160: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/49160?fields=recommendations

Fetching recommendations from MAL API:  28%|██▊       | 3882/13898 [2:38:01<78:14:10, 28.12s/it]

Error retrieving recommendations for anime 41842: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/41842?fields=recommendations

Fetching recommendations from MAL API:  28%|██▊       | 3883/13898 [2:39:32<130:22:02, 46.86s/it]

Error retrieving recommendations for anime 5504: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/5504?fields=recommendations

Fetching recommendations from MAL API:  29%|██▉       | 4039/13898 [2:43:08<1:51:12,  1.48it/s]

Error retrieving recommendations for anime 39324: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/39324?fields=recommendations

Fetching recommendations from MAL API:  29%|██▉       | 4040/13898 [2:44:41<78:14:48, 28.57s/it]

Error retrieving recommendations for anime 2429: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2429?fields=recommendations

Fetching recommendations from MAL API:  29%|██▉       | 4041/13898 [2:46:12<129:16:36, 47.21s/it]

Error retrieving recommendations for anime 1543: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/1543?fields=recommendations

Fetching recommendations from MAL API:  30%|███       | 4199/13898 [2:49:49<1:47:02,  1.51it/s]

Error retrieving recommendations for anime 2667: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2667?fields=recommendations

Fetching recommendations from MAL API:  30%|███       | 4200/13898 [2:51:23<76:59:35, 28.58s/it]

Error retrieving recommendations for anime 53421: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/53421?fields=recommendations

Fetching recommendations from MAL API:  30%|███       | 4201/13898 [2:52:53<127:06:26, 47.19s/it]

Error retrieving recommendations for anime 32801: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/32801?fields=recommendations

Fetching recommendations from MAL API:  31%|███▏      | 4359/13898 [2:56:30<1:44:38,  1.52it/s]

Error retrieving recommendations for anime 395: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/395?fields=recommendations

Fetching recommendations from MAL API:  31%|███▏      | 4360/13898 [2:58:04<75:39:02, 28.55s/it]

Error retrieving recommendations for anime 56544: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/56544?fields=recommendations

Fetching recommendations from MAL API:  31%|███▏      | 4361/13898 [2:59:35<125:05:18, 47.22s/it]

Error retrieving recommendations for anime 18343: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/18343?fields=recommendations

Fetching recommendations from MAL API:  33%|███▎      | 4527/13898 [3:03:20<1:54:54,  1.36it/s]

Error retrieving recommendations for anime 3354: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/3354?fields=recommendations

Fetching recommendations from MAL API:  33%|███▎      | 4528/13898 [3:04:51<72:06:08, 27.70s/it]

Error retrieving recommendations for anime 9547: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/9547?fields=recommendations

Fetching recommendations from MAL API:  33%|███▎      | 4529/13898 [3:06:22<121:14:42, 46.59s/it]

Error retrieving recommendations for anime 1079: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/1079?fields=recommendations

Fetching recommendations from MAL API:  34%|███▎      | 4685/13898 [3:10:00<2:06:23,  1.21it/s]

Error retrieving recommendations for anime 7761: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/7761?fields=recommendations

Fetching recommendations from MAL API:  34%|███▎      | 4686/13898 [3:11:31<71:00:45, 27.75s/it]

Error retrieving recommendations for anime 3656: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/3656?fields=recommendations

Fetching recommendations from MAL API:  34%|███▎      | 4687/13898 [3:13:02<119:20:11, 46.64s/it]

Error retrieving recommendations for anime 30307: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/30307?fields=recommendations

Fetching recommendations from MAL API:  35%|███▍      | 4843/13898 [3:16:40<2:27:00,  1.03it/s]

Error retrieving recommendations for anime 3186: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/3186?fields=recommendations

Fetching recommendations from MAL API:  35%|███▍      | 4844/13898 [3:18:11<70:05:07, 27.87s/it]

Error retrieving recommendations for anime 40659: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/40659?fields=recommendations

Fetching recommendations from MAL API:  35%|███▍      | 4845/13898 [3:19:42<117:25:24, 46.69s/it]

Error retrieving recommendations for anime 42205: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/42205?fields=recommendations

Fetching recommendations from MAL API:  36%|███▌      | 5002/13898 [3:23:20<2:41:16,  1.09s/it]

Error retrieving recommendations for anime 1258: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/1258?fields=recommendations

Fetching recommendations from MAL API:  36%|███▌      | 5003/13898 [3:24:51<69:01:13, 27.93s/it]

Error retrieving recommendations for anime 50306: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/50306?fields=recommendations

Fetching recommendations from MAL API:  36%|███▌      | 5004/13898 [3:26:21<115:31:54, 46.76s/it]

Error retrieving recommendations for anime 31229: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/31229?fields=recommendations

Fetching recommendations from MAL API:  37%|███▋      | 5161/13898 [3:30:00<3:10:22,  1.31s/it]

Error retrieving recommendations for anime 23201: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/23201?fields=recommendations

Fetching recommendations from MAL API:  37%|███▋      | 5162/13898 [3:31:31<68:13:20, 28.11s/it]

Error retrieving recommendations for anime 28625: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/28625?fields=recommendations

Fetching recommendations from MAL API:  37%|███▋      | 5163/13898 [3:33:02<113:45:23, 46.88s/it]

Error retrieving recommendations for anime 58449: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/58449?fields=recommendations

Fetching recommendations from MAL API:  38%|███▊      | 5308/13898 [3:36:30<1:44:06,  1.38it/s]

Error retrieving recommendations for anime 53588: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/53588?fields=recommendations

Fetching recommendations from MAL API:  38%|███▊      | 5309/13898 [3:38:01<66:07:50, 27.72s/it]

Error retrieving recommendations for anime 1857: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/1857?fields=recommendations

Fetching recommendations from MAL API:  38%|███▊      | 5310/13898 [3:39:31<111:11:04, 46.61s/it]

Error retrieving recommendations for anime 50206: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/50206?fields=recommendations

Fetching recommendations from MAL API:  39%|███▉      | 5479/13898 [3:43:19<1:32:16,  1.52it/s]

Error retrieving recommendations for anime 812: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/812?fields=recommendations

Fetching recommendations from MAL API:  39%|███▉      | 5480/13898 [3:44:53<66:44:11, 28.54s/it]

Error retrieving recommendations for anime 8361: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/8361?fields=recommendations

Fetching recommendations from MAL API:  39%|███▉      | 5481/13898 [3:46:23<110:19:22, 47.19s/it]

Error retrieving recommendations for anime 292: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/292?fields=recommendations

Fetching recommendations from MAL API:  41%|████      | 5649/13898 [3:50:10<1:36:24,  1.43it/s]

Error retrieving recommendations for anime 53835: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/53835?fields=recommendations

Fetching recommendations from MAL API:  41%|████      | 5650/13898 [3:51:41<63:22:48, 27.66s/it]

Error retrieving recommendations for anime 37393: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/37393?fields=recommendations

Fetching recommendations from MAL API:  41%|████      | 5651/13898 [3:53:11<106:36:59, 46.54s/it]

Error retrieving recommendations for anime 23487: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/23487?fields=recommendations

Fetching recommendations from MAL API:  42%|████▏     | 5819/13898 [3:56:58<1:32:21,  1.46it/s]

Error retrieving recommendations for anime 300: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/300?fields=recommendations

Fetching recommendations from MAL API:  42%|████▏     | 5820/13898 [3:58:32<64:10:22, 28.60s/it]

Error retrieving recommendations for anime 27939: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/27939?fields=recommendations

Fetching recommendations from MAL API:  42%|████▏     | 5821/13898 [4:00:03<106:00:45, 47.25s/it]

Error retrieving recommendations for anime 13677: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/13677?fields=recommendations

Fetching recommendations from MAL API:  43%|████▎     | 5979/13898 [4:03:40<1:27:12,  1.51it/s]

Error retrieving recommendations for anime 5023: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/5023?fields=recommendations

Fetching recommendations from MAL API:  43%|████▎     | 5980/13898 [4:05:13<62:48:01, 28.55s/it]

Error retrieving recommendations for anime 7474: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/7474?fields=recommendations

Fetching recommendations from MAL API:  43%|████▎     | 5981/13898 [4:06:44<103:43:42, 47.17s/it]

Error retrieving recommendations for anime 40807: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/40807?fields=recommendations

Fetching recommendations from MAL API:  44%|████▍     | 6122/13898 [4:10:10<2:27:28,  1.14s/it]

Error retrieving recommendations for anime 39417: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/39417?fields=recommendations

Fetching recommendations from MAL API:  44%|████▍     | 6123/13898 [4:11:41<60:29:03, 28.01s/it]

Error retrieving recommendations for anime 39605: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/39605?fields=recommendations

Fetching recommendations from MAL API:  44%|████▍     | 6124/13898 [4:13:11<101:04:27, 46.81s/it]

Error retrieving recommendations for anime 56561: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/56561?fields=recommendations

Fetching recommendations from MAL API:  45%|████▌     | 6294/13898 [4:17:00<1:24:20,  1.50it/s]

Error retrieving recommendations for anime 7366: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/7366?fields=recommendations

Fetching recommendations from MAL API:  45%|████▌     | 6295/13898 [4:18:31<58:24:08, 27.65s/it]

Error retrieving recommendations for anime 37828: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/37828?fields=recommendations

Fetching recommendations from MAL API:  45%|████▌     | 6296/13898 [4:20:01<98:17:41, 46.55s/it]

Error retrieving recommendations for anime 2131: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2131?fields=recommendations

Fetching recommendations from MAL API:  46%|████▋     | 6462/13898 [4:23:50<2:19:24,  1.12s/it]

Error retrieving recommendations for anime 43204: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/43204?fields=recommendations

Fetching recommendations from MAL API:  47%|████▋     | 6463/13898 [4:25:21<57:47:54, 27.99s/it]

Error retrieving recommendations for anime 5036: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/5036?fields=recommendations

Fetching recommendations from MAL API:  47%|████▋     | 6464/13898 [4:26:51<96:39:47, 46.81s/it]

Error retrieving recommendations for anime 9362: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/9362?fields=recommendations

Fetching recommendations from MAL API:  48%|████▊     | 6620/13898 [4:30:30<3:14:06,  1.60s/it]

Error retrieving recommendations for anime 3646: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/3646?fields=recommendations

Fetching recommendations from MAL API:  48%|████▊     | 6621/13898 [4:32:01<57:14:35, 28.32s/it]

Error retrieving recommendations for anime 24695: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/24695?fields=recommendations

Fetching recommendations from MAL API:  48%|████▊     | 6622/13898 [4:33:31<95:02:43, 47.03s/it]

Error retrieving recommendations for anime 1466: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/1466?fields=recommendations

Fetching recommendations from MAL API:  49%|████▉     | 6779/13898 [4:37:08<1:20:58,  1.47it/s]

Error retrieving recommendations for anime 44390: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/44390?fields=recommendations

Fetching recommendations from MAL API:  49%|████▉     | 6780/13898 [4:38:42<56:28:50, 28.57s/it]

Error retrieving recommendations for anime 37920: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/37920?fields=recommendations

Fetching recommendations from MAL API:  49%|████▉     | 6781/13898 [4:40:13<93:20:05, 47.21s/it]

Error retrieving recommendations for anime 20267: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/20267?fields=recommendations

Fetching recommendations from MAL API:  50%|█████     | 6950/13898 [4:44:00<1:20:41,  1.44it/s]

Error retrieving recommendations for anime 7245: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/7245?fields=recommendations

Fetching recommendations from MAL API:  50%|█████     | 6951/13898 [4:45:31<53:22:51, 27.66s/it]

Error retrieving recommendations for anime 28283: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/28283?fields=recommendations

Fetching recommendations from MAL API:  50%|█████     | 6952/13898 [4:47:01<89:47:47, 46.54s/it]

Error retrieving recommendations for anime 52101: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/52101?fields=recommendations

Fetching recommendations from MAL API:  51%|█████     | 7108/13898 [4:50:42<1:22:29,  1.37it/s]

Error retrieving recommendations for anime 43767: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/43767?fields=recommendations

Fetching recommendations from MAL API:  51%|█████     | 7109/13898 [4:52:12<52:15:08, 27.71s/it]

Error retrieving recommendations for anime 58015: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/58015?fields=recommendations

Fetching recommendations from MAL API:  51%|█████     | 7110/13898 [4:53:43<87:50:13, 46.58s/it]

Error retrieving recommendations for anime 682: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/682?fields=recommendations

Fetching recommendations from MAL API:  52%|█████▏    | 7266/13898 [4:57:22<1:27:18,  1.27it/s]

Error retrieving recommendations for anime 2089: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2089?fields=recommendations

Fetching recommendations from MAL API:  52%|█████▏    | 7267/13898 [4:58:52<51:04:13, 27.73s/it]

Error retrieving recommendations for anime 9479: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/9479?fields=recommendations

Fetching recommendations from MAL API:  52%|█████▏    | 7268/13898 [5:00:23<85:47:43, 46.59s/it]

Error retrieving recommendations for anime 5618: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/5618?fields=recommendations

Fetching recommendations from MAL API:  53%|█████▎    | 7424/13898 [5:04:02<1:34:05,  1.15it/s]

Error retrieving recommendations for anime 41372: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/41372?fields=recommendations

Fetching recommendations from MAL API:  53%|█████▎    | 7425/13898 [5:05:32<49:57:38, 27.79s/it]

Error retrieving recommendations for anime 4173: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/4173?fields=recommendations

Fetching recommendations from MAL API:  53%|█████▎    | 7426/13898 [5:07:03<83:53:58, 46.67s/it]

Error retrieving recommendations for anime 39194: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/39194?fields=recommendations

Fetching recommendations from MAL API:  55%|█████▍    | 7597/13898 [5:10:52<1:10:52,  1.48it/s]

Error retrieving recommendations for anime 23897: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/23897?fields=recommendations

Fetching recommendations from MAL API:  55%|█████▍    | 7598/13898 [5:12:22<48:25:31, 27.67s/it]

Error retrieving recommendations for anime 32321: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/32321?fields=recommendations

Fetching recommendations from MAL API:  55%|█████▍    | 7599/13898 [5:13:53<81:27:58, 46.56s/it]

Error retrieving recommendations for anime 1495: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/1495?fields=recommendations

Fetching recommendations from MAL API:  56%|█████▌    | 7763/13898 [5:17:41<1:40:55,  1.01it/s]

Error retrieving recommendations for anime 23581: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/23581?fields=recommendations

Fetching recommendations from MAL API:  56%|█████▌    | 7764/13898 [5:19:12<47:30:08, 27.88s/it]

Error retrieving recommendations for anime 44213: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/44213?fields=recommendations

Fetching recommendations from MAL API:  56%|█████▌    | 7765/13898 [5:20:42<79:33:54, 46.70s/it]

Error retrieving recommendations for anime 5742: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/5742?fields=recommendations

Fetching recommendations from MAL API:  57%|█████▋    | 7911/13898 [5:24:11<1:08:11,  1.46it/s]

Error retrieving recommendations for anime 39523: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/39523?fields=recommendations

Fetching recommendations from MAL API:  57%|█████▋    | 7912/13898 [5:25:42<45:59:40, 27.66s/it]

Error retrieving recommendations for anime 37424: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/37424?fields=recommendations

Fetching recommendations from MAL API:  57%|█████▋    | 7913/13898 [5:27:13<77:24:09, 46.56s/it]

Error retrieving recommendations for anime 3202: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/3202?fields=recommendations

Fetching recommendations from MAL API:  58%|█████▊    | 8079/13898 [5:30:59<1:03:53,  1.52it/s]

Error retrieving recommendations for anime 9535: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/9535?fields=recommendations

Fetching recommendations from MAL API:  58%|█████▊    | 8080/13898 [5:32:33<46:08:31, 28.55s/it]

Error retrieving recommendations for anime 8450: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/8450?fields=recommendations

Fetching recommendations from MAL API:  58%|█████▊    | 8081/13898 [5:34:03<76:15:15, 47.19s/it]

Error retrieving recommendations for anime 14145: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/14145?fields=recommendations

Fetching recommendations from MAL API:  59%|█████▉    | 8239/13898 [5:37:40<1:05:14,  1.45it/s]

Error retrieving recommendations for anime 49871: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/49871?fields=recommendations

Fetching recommendations from MAL API:  59%|█████▉    | 8240/13898 [5:39:14<44:55:06, 28.58s/it]

Error retrieving recommendations for anime 13639: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/13639?fields=recommendations

Fetching recommendations from MAL API:  59%|█████▉    | 8241/13898 [5:40:44<74:11:22, 47.21s/it]

Error retrieving recommendations for anime 39295: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/39295?fields=recommendations

Fetching recommendations from MAL API:  60%|██████    | 8399/13898 [5:44:21<1:00:43,  1.51it/s]

Error retrieving recommendations for anime 1862: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/1862?fields=recommendations

Fetching recommendations from MAL API:  60%|██████    | 8400/13898 [5:45:55<43:37:47, 28.57s/it]

Error retrieving recommendations for anime 2366: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2366?fields=recommendations

Fetching recommendations from MAL API:  60%|██████    | 8401/13898 [5:47:25<72:04:47, 47.21s/it]

Error retrieving recommendations for anime 12861: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/12861?fields=recommendations

Fetching recommendations from MAL API:  62%|██████▏   | 8557/13898 [5:51:01<59:44,  1.49it/s]

Error retrieving recommendations for anime 11859: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/11859?fields=recommendations

Fetching recommendations from MAL API:  62%|██████▏   | 8558/13898 [5:52:32<41:02:21, 27.67s/it]

Error retrieving recommendations for anime 31540: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/31540?fields=recommendations

Fetching recommendations from MAL API:  62%|██████▏   | 8559/13898 [5:54:03<69:03:02, 46.56s/it]

Error retrieving recommendations for anime 50644: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/50644?fields=recommendations

Fetching recommendations from MAL API:  63%|██████▎   | 8714/13898 [5:57:41<59:56,  1.44it/s]

Error retrieving recommendations for anime 29603: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/29603?fields=recommendations

Fetching recommendations from MAL API:  63%|██████▎   | 8715/13898 [5:59:12<39:52:08, 27.69s/it]

Error retrieving recommendations for anime 7376: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/7376?fields=recommendations

Fetching recommendations from MAL API:  63%|██████▎   | 8716/13898 [6:00:43<67:04:46, 46.60s/it]

Error retrieving recommendations for anime 51764: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/51764?fields=recommendations

Fetching recommendations from MAL API:  64%|██████▍   | 8872/13898 [6:04:22<56:11,  1.49it/s]

Error retrieving recommendations for anime 14935: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/14935?fields=recommendations

Fetching recommendations from MAL API:  64%|██████▍   | 8873/13898 [6:05:52<38:38:06, 27.68s/it]

Error retrieving recommendations for anime 14583: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/14583?fields=recommendations

Fetching recommendations from MAL API:  64%|██████▍   | 8874/13898 [6:07:23<65:00:02, 46.58s/it]

Error retrieving recommendations for anime 9078: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/9078?fields=recommendations

Fetching recommendations from MAL API:  65%|██████▌   | 9039/13898 [6:11:09<55:44,  1.45it/s]

Error retrieving recommendations for anime 24873: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/24873?fields=recommendations

Fetching recommendations from MAL API:  65%|██████▌   | 9040/13898 [6:12:42<38:34:06, 28.58s/it]

Error retrieving recommendations for anime 3153: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/3153?fields=recommendations

Fetching recommendations from MAL API:  65%|██████▌   | 9041/13898 [6:14:13<63:42:56, 47.23s/it]

Error retrieving recommendations for anime 27837: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/27837?fields=recommendations

Fetching recommendations from MAL API:  66%|██████▋   | 9210/13898 [6:18:02<58:28,  1.34it/s]

Error retrieving recommendations for anime 49290: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/49290?fields=recommendations

Fetching recommendations from MAL API:  66%|██████▋   | 9211/13898 [6:19:32<36:05:58, 27.73s/it]

Error retrieving recommendations for anime 24417: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/24417?fields=recommendations

Fetching recommendations from MAL API:  66%|██████▋   | 9212/13898 [6:21:03<60:40:01, 46.61s/it]

Error retrieving recommendations for anime 8743: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/8743?fields=recommendations

Fetching recommendations from MAL API:  67%|██████▋   | 9365/13898 [6:24:41<1:02:06,  1.22it/s]

Error retrieving recommendations for anime 9824: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/9824?fields=recommendations

Fetching recommendations from MAL API:  67%|██████▋   | 9366/13898 [6:26:12<34:55:49, 27.75s/it]

Error retrieving recommendations for anime 50849: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/50849?fields=recommendations

Fetching recommendations from MAL API:  67%|██████▋   | 9367/13898 [6:27:43<58:42:19, 46.64s/it]

Error retrieving recommendations for anime 36196: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/36196?fields=recommendations

Fetching recommendations from MAL API:  68%|██████▊   | 9512/13898 [6:31:12<49:35,  1.47it/s]

Error retrieving recommendations for anime 2535: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2535?fields=recommendations

Fetching recommendations from MAL API:  68%|██████▊   | 9513/13898 [6:32:42<33:40:44, 27.65s/it]

Error retrieving recommendations for anime 12447: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/12447?fields=recommendations

Fetching recommendations from MAL API:  68%|██████▊   | 9514/13898 [6:34:13<56:44:03, 46.59s/it]

Error retrieving recommendations for anime 9613: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/9613?fields=recommendations

Fetching recommendations from MAL API:  70%|██████▉   | 9679/13898 [6:37:58<47:12,  1.49it/s]

Error retrieving recommendations for anime 34961: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/34961?fields=recommendations

Fetching recommendations from MAL API:  70%|██████▉   | 9680/13898 [6:39:32<33:28:05, 28.56s/it]

Error retrieving recommendations for anime 61224: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/61224?fields=recommendations

Fetching recommendations from MAL API:  70%|██████▉   | 9681/13898 [6:41:02<55:15:46, 47.18s/it]

Error retrieving recommendations for anime 3080: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/3080?fields=recommendations

Fetching recommendations from MAL API:  71%|███████   | 9839/13898 [6:44:40<45:04,  1.50it/s]

Error retrieving recommendations for anime 2760: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2760?fields=recommendations

Fetching recommendations from MAL API:  71%|███████   | 9840/13898 [6:46:13<32:12:37, 28.58s/it]

Error retrieving recommendations for anime 8491: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/8491?fields=recommendations

Fetching recommendations from MAL API:  71%|███████   | 9841/13898 [6:47:44<53:12:19, 47.21s/it]

Error retrieving recommendations for anime 28371: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/28371?fields=recommendations

Fetching recommendations from MAL API:  72%|███████▏  | 9998/13898 [6:51:21<43:46,  1.48it/s]

Error retrieving recommendations for anime 3277: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/3277?fields=recommendations

Fetching recommendations from MAL API:  72%|███████▏  | 9999/13898 [6:52:52<29:56:21, 27.64s/it]

Error retrieving recommendations for anime 766: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/766?fields=recommendations

Fetching recommendations from MAL API:  72%|███████▏  | 10000/13898 [6:54:26<51:24:01, 47.47s/it]

Error retrieving recommendations for anime 29517: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/29517?fields=recommendations

Fetching recommendations from MAL API:  73%|███████▎  | 10165/13898 [6:58:11<50:45,  1.23it/s]

Error retrieving recommendations for anime 16970: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/16970?fields=recommendations

Fetching recommendations from MAL API:  73%|███████▎  | 10166/13898 [6:59:42<28:46:29, 27.76s/it]

Error retrieving recommendations for anime 9015: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/9015?fields=recommendations

Fetching recommendations from MAL API:  73%|███████▎  | 10167/13898 [7:01:13<48:19:02, 46.62s/it]

Error retrieving recommendations for anime 40438: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/40438?fields=recommendations

Fetching recommendations from MAL API:  74%|███████▍  | 10322/13898 [7:04:52<1:06:31,  1.12s/it]

Error retrieving recommendations for anime 9990: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/9990?fields=recommendations

Fetching recommendations from MAL API:  74%|███████▍  | 10323/13898 [7:06:22<27:45:37, 27.95s/it]

Error retrieving recommendations for anime 53084: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/53084?fields=recommendations

Fetching recommendations from MAL API:  74%|███████▍  | 10324/13898 [7:07:53<46:25:24, 46.76s/it]

Error retrieving recommendations for anime 8960: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/8960?fields=recommendations

Fetching recommendations from MAL API:  75%|███████▌  | 10479/13898 [7:11:28<38:37,  1.48it/s]

Error retrieving recommendations for anime 19627: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/19627?fields=recommendations

Fetching recommendations from MAL API:  75%|███████▌  | 10480/13898 [7:13:02<27:07:15, 28.57s/it]

Error retrieving recommendations for anime 27997: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/27997?fields=recommendations

Fetching recommendations from MAL API:  75%|███████▌  | 10481/13898 [7:14:32<44:47:26, 47.19s/it]

Error retrieving recommendations for anime 2304: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/2304?fields=recommendations

Fetching recommendations from MAL API:  77%|███████▋  | 10639/13898 [7:18:10<36:04,  1.51it/s]

Error retrieving recommendations for anime 22413: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/22413?fields=recommendations

Fetching recommendations from MAL API:  77%|███████▋  | 10640/13898 [7:19:44<25:50:32, 28.56s/it]

Error retrieving recommendations for anime 39482: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/39482?fields=recommendations

Fetching recommendations from MAL API:  77%|███████▋  | 10641/13898 [7:21:15<42:42:46, 47.21s/it]

Error retrieving recommendations for anime 13673: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/13673?fields=recommendations

Fetching recommendations from MAL API:  78%|███████▊  | 10808/13898 [7:25:01<37:19,  1.38it/s]

Error retrieving recommendations for anime 14183: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/14183?fields=recommendations

Fetching recommendations from MAL API:  78%|███████▊  | 10809/13898 [7:26:32<23:46:20, 27.70s/it]

Error retrieving recommendations for anime 8227: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/8227?fields=recommendations

Fetching recommendations from MAL API:  78%|███████▊  | 10810/13898 [7:28:02<39:57:46, 46.59s/it]

Error retrieving recommendations for anime 33184: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/33184?fields=recommendations

Fetching recommendations from MAL API:  79%|███████▉  | 10966/13898 [7:31:42<38:23,  1.27it/s]

Error retrieving recommendations for anime 3849: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/3849?fields=recommendations

Fetching recommendations from MAL API:  79%|███████▉  | 10967/13898 [7:33:12<22:34:20, 27.72s/it]

Error retrieving recommendations for anime 38290: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/38290?fields=recommendations

Fetching recommendations from MAL API:  79%|███████▉  | 10968/13898 [7:34:43<37:55:47, 46.60s/it]

Error retrieving recommendations for anime 10261: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/10261?fields=recommendations

Fetching recommendations from MAL API:  80%|████████  | 11137/13898 [7:38:32<31:36,  1.46it/s]

Error retrieving recommendations for anime 20835: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/20835?fields=recommendations

Fetching recommendations from MAL API:  80%|████████  | 11138/13898 [7:40:02<21:15:22, 27.73s/it]

Error retrieving recommendations for anime 37529: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/37529?fields=recommendations

Fetching recommendations from MAL API:  80%|████████  | 11139/13898 [7:41:33<35:44:17, 46.63s/it]

Error retrieving recommendations for anime 35007: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/35007?fields=recommendations

Fetching recommendations from MAL API:  81%|████████▏ | 11293/13898 [7:45:12<29:53,  1.45it/s]

Error retrieving recommendations for anime 38667: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/38667?fields=recommendations

Fetching recommendations from MAL API:  81%|████████▏ | 11294/13898 [7:46:42<20:00:10, 27.65s/it]

Error retrieving recommendations for anime 37753: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/37753?fields=recommendations

Fetching recommendations from MAL API:  81%|████████▏ | 11295/13898 [7:48:13<33:40:02, 46.56s/it]

Error retrieving recommendations for anime 4085: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/4085?fields=recommendations

Fetching recommendations from MAL API:  82%|████████▏ | 11459/13898 [7:51:58<27:43,  1.47it/s]

Error retrieving recommendations for anime 3104: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/3104?fields=recommendations

Fetching recommendations from MAL API:  82%|████████▏ | 11460/13898 [7:53:32<19:21:43, 28.59s/it]

Error retrieving recommendations for anime 37663: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/37663?fields=recommendations

Fetching recommendations from MAL API:  82%|████████▏ | 11461/13898 [7:55:03<31:58:27, 47.23s/it]

Error retrieving recommendations for anime 29267: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/29267?fields=recommendations

Fetching recommendations from MAL API:  84%|████████▎ | 11619/13898 [7:58:41<25:50,  1.47it/s]

Error retrieving recommendations for anime 22619: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/22619?fields=recommendations

Fetching recommendations from MAL API:  84%|████████▎ | 11620/13898 [8:00:15<18:05:11, 28.58s/it]

Error retrieving recommendations for anime 32259: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/32259?fields=recommendations

Fetching recommendations from MAL API:  84%|████████▎ | 11621/13898 [8:01:45<29:51:39, 47.21s/it]

Error retrieving recommendations for anime 51150: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/51150?fields=recommendations

Fetching recommendations from MAL API:  85%|████████▍ | 11799/13898 [8:05:39<23:11,  1.51it/s]

Error retrieving recommendations for anime 574: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/574?fields=recommendations

Fetching recommendations from MAL API:  85%|████████▍ | 11800/13898 [8:07:13<16:39:01, 28.57s/it]

Error retrieving recommendations for anime 29797: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/29797?fields=recommendations

Fetching recommendations from MAL API:  85%|████████▍ | 11801/13898 [8:08:44<27:29:42, 47.20s/it]

Error retrieving recommendations for anime 9212: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/9212?fields=recommendations

Fetching recommendations from MAL API:  86%|████████▌ | 11971/13898 [8:12:32<22:00,  1.46it/s]

Error retrieving recommendations for anime 51078: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/51078?fields=recommendations

Fetching recommendations from MAL API:  86%|████████▌ | 11972/13898 [8:14:02<14:47:42, 27.65s/it]

Error retrieving recommendations for anime 16696: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/16696?fields=recommendations

Fetching recommendations from MAL API:  86%|████████▌ | 11973/13898 [8:15:33<24:53:33, 46.55s/it]

Error retrieving recommendations for anime 43506: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/43506?fields=recommendations

Fetching recommendations from MAL API:  87%|████████▋ | 12128/13898 [8:19:11<21:57,  1.34it/s]

Error retrieving recommendations for anime 55714: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/55714?fields=recommendations

Fetching recommendations from MAL API:  87%|████████▋ | 12129/13898 [8:20:42<13:36:53, 27.71s/it]

Error retrieving recommendations for anime 31926: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/31926?fields=recommendations

Fetching recommendations from MAL API:  87%|████████▋ | 12130/13898 [8:22:13<22:53:35, 46.62s/it]

Error retrieving recommendations for anime 38386: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/38386?fields=recommendations

Fetching recommendations from MAL API:  88%|████████▊ | 12284/13898 [8:25:51<24:00,  1.12it/s]

Error retrieving recommendations for anime 7258: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/7258?fields=recommendations

Fetching recommendations from MAL API:  88%|████████▊ | 12285/13898 [8:27:22<12:27:16, 27.80s/it]

Error retrieving recommendations for anime 40721: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/40721?fields=recommendations

Fetching recommendations from MAL API:  88%|████████▊ | 12286/13898 [8:28:53<20:53:54, 46.67s/it]

Error retrieving recommendations for anime 31259: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/31259?fields=recommendations

Fetching recommendations from MAL API:  90%|████████▉ | 12440/13898 [8:32:32<38:38,  1.59s/it]

Error retrieving recommendations for anime 18133: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/18133?fields=recommendations

Fetching recommendations from MAL API:  90%|████████▉ | 12441/13898 [8:34:02<11:27:29, 28.31s/it]

Error retrieving recommendations for anime 40338: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/40338?fields=recommendations

Fetching recommendations from MAL API:  90%|████████▉ | 12442/13898 [8:35:33<19:01:15, 47.03s/it]

Error retrieving recommendations for anime 29791: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/29791?fields=recommendations

Fetching recommendations from MAL API:  91%|█████████ | 12599/13898 [8:39:10<14:22,  1.51it/s]

Error retrieving recommendations for anime 36524: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/36524?fields=recommendations

Fetching recommendations from MAL API:  91%|█████████ | 12600/13898 [8:40:44<10:17:35, 28.55s/it]

Error retrieving recommendations for anime 27785: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/27785?fields=recommendations

Fetching recommendations from MAL API:  91%|█████████ | 12601/13898 [8:42:15<17:00:35, 47.21s/it]

Error retrieving recommendations for anime 25973: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/25973?fields=recommendations

Fetching recommendations from MAL API:  92%|█████████▏| 12757/13898 [8:45:51<12:48,  1.49it/s]

Error retrieving recommendations for anime 20087: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/20087?fields=recommendations

Fetching recommendations from MAL API:  92%|█████████▏| 12758/13898 [8:47:22<8:45:33, 27.66s/it]

Error retrieving recommendations for anime 28245: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/28245?fields=recommendations

Fetching recommendations from MAL API:  92%|█████████▏| 12759/13898 [8:48:52<14:44:02, 46.57s/it]

Error retrieving recommendations for anime 34716: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/34716?fields=recommendations

Fetching recommendations from MAL API:  93%|█████████▎| 12939/13898 [8:52:51<10:44,  1.49it/s]

Error retrieving recommendations for anime 55717: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/55717?fields=recommendations

Fetching recommendations from MAL API:  93%|█████████▎| 12940/13898 [8:54:25<7:36:03, 28.56s/it]

Error retrieving recommendations for anime 49491: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/49491?fields=recommendations

Fetching recommendations from MAL API:  93%|█████████▎| 12941/13898 [8:55:56<12:32:59, 47.21s/it]

Error retrieving recommendations for anime 1626: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/1626?fields=recommendations

Fetching recommendations from MAL API:  94%|█████████▍| 13095/13898 [8:59:31<09:08,  1.46it/s]

Error retrieving recommendations for anime 30850: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/30850?fields=recommendations

Fetching recommendations from MAL API:  94%|█████████▍| 13096/13898 [9:01:02<6:10:06, 27.69s/it]

Error retrieving recommendations for anime 32644: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/32644?fields=recommendations

Fetching recommendations from MAL API:  94%|█████████▍| 13097/13898 [9:02:33<10:21:48, 46.58s/it]

Error retrieving recommendations for anime 13087: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/13087?fields=recommendations

Fetching recommendations from MAL API:  95%|█████████▌| 13260/13898 [9:06:21<16:40,  1.57s/it]

Error retrieving recommendations for anime 28953: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/28953?fields=recommendations

Fetching recommendations from MAL API:  95%|█████████▌| 13261/13898 [9:07:52<5:00:32, 28.31s/it]

Error retrieving recommendations for anime 7243: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/7243?fields=recommendations

Fetching recommendations from MAL API:  95%|█████████▌| 13262/13898 [9:09:22<8:18:25, 47.02s/it]

Error retrieving recommendations for anime 34628: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/34628?fields=recommendations

Fetching recommendations from MAL API:  97%|█████████▋| 13419/13898 [9:13:01<05:30,  1.45it/s]

Error retrieving recommendations for anime 1355: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/1355?fields=recommendations

Fetching recommendations from MAL API:  97%|█████████▋| 13420/13898 [9:14:34<3:47:38, 28.57s/it]

Error retrieving recommendations for anime 32296: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/32296?fields=recommendations

Fetching recommendations from MAL API:  97%|█████████▋| 13421/13898 [9:16:05<6:15:24, 47.22s/it]

Error retrieving recommendations for anime 37408: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/37408?fields=recommendations

Fetching recommendations from MAL API:  98%|█████████▊| 13576/13898 [9:19:41<03:41,  1.45it/s]

Error retrieving recommendations for anime 38017: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/38017?fields=recommendations

Fetching recommendations from MAL API:  98%|█████████▊| 13577/13898 [9:21:12<2:28:03, 27.67s/it]

Error retrieving recommendations for anime 18703: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/18703?fields=recommendations

Fetching recommendations from MAL API:  98%|█████████▊| 13578/13898 [9:22:43<4:08:23, 46.57s/it]

Error retrieving recommendations for anime 48680: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/48680?fields=recommendations

Fetching recommendations from MAL API:  99%|█████████▉| 13732/13898 [9:26:21<01:54,  1.46it/s]

Error retrieving recommendations for anime 28831: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/28831?fields=recommendations

Fetching recommendations from MAL API:  99%|█████████▉| 13733/13898 [9:27:52<1:16:07, 27.68s/it]

Error retrieving recommendations for anime 29597: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/29597?fields=recommendations

Fetching recommendations from MAL API:  99%|█████████▉| 13734/13898 [9:29:23<2:07:18, 46.58s/it]

Error retrieving recommendations for anime 28645: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/28645?fields=recommendations

Fetching recommendations from MAL API: 100%|██████████| 13898/13898 [9:33:10<00:00,  2.47s/it]

Successfully retrieved recommendations for 13898 anime

In [8]:
anime_manager.save_data_to_json(recommendations, 'anime_recommendations_full.json')

Data saved to anime_recommendations_full.json

'anime_recommendations_full.json'

In [24]:
with open('anime_recommendations_0_100.json') as f:
    recs = json.load(f)

In [33]:
for key,value in recs.items():
    print(f"Anime ID: {key}")
    print(f"Recommendations: {value}")

Anime ID: 52991
Recommendations: [{'node': {'id': 33352, 'title': 'Violet Evergarden', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1795/95088.webp', 'large': 'https://cdn.myanimelist.net/images/anime/1795/95088l.webp'}}, 'num_recommendations': 23}, {'node': {'id': 41025, 'title': 'Fumetsu no Anata e', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1880/118484.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1880/118484l.jpg'}}, 'num_recommendations': 15}, {'node': {'id': 35851, 'title': 'Sayonara no Asa ni Yakusoku no Hana wo Kazarou', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/11/89556.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/11/89556l.jpg'}}, 'num_recommendations': 13}, {'node': {'id': 52701, 'title': 'Dungeon Meshi', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1711/142478.webp', 'large': 'https://cdn.myanimelist.net/images/anime/1711/142478l.webp'}}, 'num_recommendations': 9}, {'node': {'id': 457, 'title': 'Mushishi', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/2/73862.webp', 'large': 'https://cdn.myanimelist.net/images/anime/2/73862l.webp'}}, 'num_recommendations': 7}, {'node': {'id': 40571, 'title': 'Majo no Tabitabi', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1802/108501.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1802/108501l.jpg'}}, 'num_recommendations': 7}, {'node': {'id': 486, 'title': 'Kino no Tabi: The Beautiful World', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1763/95397.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1763/95397l.jpg'}}, 'num_recommendations': 6}, {'node': {'id': 39535, 'title': 'Mushoku Tensei: Isekai Ittara Honki Dasu', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1530/117776.webp', 'large': 'https://cdn.myanimelist.net/images/anime/1530/117776l.webp'}}, 'num_recommendations': 6}, {'node': {'id': 2966, 'title': 'Ookami to Koushinryou', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/5/59401.webp', 'large': 'https://cdn.myanimelist.net/images/anime/5/59401l.webp'}}, 'num_recommendations': 6}, {'node': {'id': 4081, 'title': 'Natsume Yuujinchou', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1681/108439.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1681/108439l.jpg'}}, 'num_recommendations': 3}]
Anime ID: 5114
Recommendations: [{'node': {'id': 11061, 'title': 'Hunter x Hunter (2011)', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1337/99013.webp', 'large': 'https://cdn.myanimelist.net/images/anime/1337/99013l.webp'}}, 'num_recommendations': 75}, {'node': {'id': 16498, 'title': 'Shingeki no Kyojin', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/10/47347.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/10/47347l.jpg'}}, 'num_recommendations': 45}, {'node': {'id': 1482, 'title': 'D.Gray-man', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/13/75194.webp', 'large': 'https://cdn.myanimelist.net/images/anime/13/75194l.webp'}}, 'num_recommendations': 23}, {'node': {'id': 9919, 'title': 'Ao no Exorcist', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/10/75195.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/10/75195l.jpg'}}, 'num_recommendations': 17}, {'node': {'id': 38000, 'title': 'Kimetsu no Yaiba', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1286/99889.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg'}}, 'num_recommendations': 17}, {'node': {'id': 1575, 'title': 'Code Geass: Hangyaku no Lelouch', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1032/135088.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1032/135088l.jpg'}}, 'num_recommendations': 16}, {'node': {'id': 2251, 'title': 'Baccano!', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/3/14547.webp', 'large': 'https://cdn.myanimelist.net/images/anime/3/14547l.webp'}}, 'num_recommendations': 15}, {'node': {'id': 22199, 'title': 'Akame ga Kill!', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1429/95946.webp', 'large': 'https://cdn.myanimelist.net/images/anime/1429/95946l.webp'}}, 'num_recommendations': 10}, {'node': {'id': 1735, 'title': 'Naruto: Shippuuden', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1565/111305.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1565/111305l.jpg'}}, 'num_recommendations': 9}, {'node': {'id': 23755, 'title': 'Nanatsu no Taizai', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/8/65409.webp', 'large': 'https://cdn.myanimelist.net/images/anime/8/65409l.webp'}}, 'num_recommendations': 9}]
Anime ID: 9253
Recommendations: [{'node': {'id': 31043, 'title': 'Boku dake ga Inai Machi', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/10/77957.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/10/77957l.jpg'}}, 'num_recommendations': 132}, {'node': {'id': 31240, 'title': 'Re:Zero kara Hajimeru Isekai Seikatsu', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1522/128039.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1522/128039l.jpg'}}, 'num_recommendations': 132}, {'node': {'id': 9756, 'title': 'Mahou Shoujo Madoka★Magica', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/11/55225.webp', 'large': 'https://cdn.myanimelist.net/images/anime/11/55225l.webp'}}, 'num_recommendations': 49}, {'node': {'id': 10620, 'title': 'Mirai Nikki (TV)', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/13/33465.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/13/33465l.jpg'}}, 'num_recommendations': 26}, {'node': {'id': 44074, 'title': 'Shiguang Dailiren', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1135/114867.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1135/114867l.jpg'}}, 'num_recommendations': 23}, {'node': {'id': 2236, 'title': 'Toki wo Kakeru Shoujo', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1/2432.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1/2432l.jpg'}}, 'num_recommendations': 23}, {'node': {'id': 1210, 'title': 'NHK ni Youkoso!', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/3/52675.webp', 'large': 'https://cdn.myanimelist.net/images/anime/3/52675l.webp'}}, 'num_recommendations': 19}, {'node': {'id': 47194, 'title': 'Summertime Render', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1120/120796.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1120/120796l.jpg'}}, 'num_recommendations': 15}, {'node': {'id': 1535, 'title': 'Death Note', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1079/138100.webp', 'large': 'https://cdn.myanimelist.net/images/anime/1079/138100l.webp'}}, 'num_recommendations': 15}, {'node': {'id': 46095, 'title': "Vivy: Fluorite Eye's Song", 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1551/128960.webp', 'large': 'https://cdn.myanimelist.net/images/anime/1551/128960l.webp'}}, 'num_recommendations': 14}]
Anime ID: 38524
Recommendations: [{'node': {'id': 28623, 'title': 'Koutetsujou no Kabaneri', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/12/79164.webp', 'large': 'https://cdn.myanimelist.net/images/anime/12/79164l.webp'}}, 'num_recommendations': 2}, {'node': {'id': 35557, 'title': 'Houseki no Kuni', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/3/88293.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/3/88293l.jpg'}}, 'num_recommendations': 1}, {'node': {'id': 26243, 'title': 'Owari no Seraph', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1879/148979.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1879/148979l.jpg'}}, 'num_recommendations': 1}, {'node': {'id': 31240, 'title': 'Re:Zero kara Hajimeru Isekai Seikatsu', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1522/128039.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1522/128039l.jpg'}}, 'num_recommendations': 1}, {'node': {'id': 32935, 'title': 'Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen Koukou', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/7/81992.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/7/81992l.jpg'}}, 'num_recommendations': 1}, {'node': {'id': 40682, 'title': 'Kingdom 3rd Season', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1443/111830.webp', 'large': 'https://cdn.myanimelist.net/images/anime/1443/111830l.webp'}}, 'num_recommendations': 1}, {'node': {'id': 1535, 'title': 'Death Note', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1079/138100.webp', 'large': 'https://cdn.myanimelist.net/images/anime/1079/138100l.webp'}}, 'num_recommendations': 1}, {'node': {'id': 2904, 'title': 'Code Geass: Hangyaku no Lelouch R2', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1088/135089.webp', 'large': 'https://cdn.myanimelist.net/images/anime/1088/135089l.webp'}}, 'num_recommendations': 1}, {'node': {'id': 37521, 'title': 'Vinland Saga', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1500/103005.webp', 'large': 'https://cdn.myanimelist.net/images/anime/1500/103005l.webp'}}, 'num_recommendations': 1}, {'node': {'id': 25781, 'title': 'Shingeki no Kyojin: Kuinaki Sentaku', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/8/69497.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/8/69497l.jpg'}}, 'num_recommendations': 1}]
Anime ID: 60022
Recommendations: []
Anime ID: 28977
Recommendations: [{'node': {'id': 9863, 'title': 'SKET Dance', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/9/73974.webp', 'large': 'https://cdn.myanimelist.net/images/anime/9/73974l.webp'}}, 'num_recommendations': 4}, {'node': {'id': 30276, 'title': 'One Punch Man', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/12/76049.webp', 'large': 'https://cdn.myanimelist.net/images/anime/12/76049l.webp'}}, 'num_recommendations': 3}, {'node': {'id': 6347, 'title': 'Baka to Test to Shoukanjuu', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/3/50389.webp', 'large': 'https://cdn.myanimelist.net/images/anime/3/50389l.webp'}}, 'num_recommendations': 2}, {'node': {'id': 37105, 'title': 'Grand Blue', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1302/94882.webp', 'large': 'https://cdn.myanimelist.net/images/anime/1302/94882l.webp'}}, 'num_recommendations': 2}, {'node': {'id': 32937, 'title': 'Kono Subarashii Sekai ni Shukufuku wo! 2', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/2/83188.webp', 'large': 'https://cdn.myanimelist.net/images/anime/2/83188l.webp'}}, 'num_recommendations': 1}, {'node': {'id': 9253, 'title': 'Steins;Gate', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1935/127974.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1935/127974l.jpg'}}, 'num_recommendations': 1}, {'node': {'id': 44042, 'title': 'Holo no Graffiti', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1259/110227.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1259/110227l.jpg'}}, 'num_recommendations': 1}, {'node': {'id': 20507, 'title': 'Noragami', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1886/128266.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1886/128266l.jpg'}}, 'num_recommendations': 1}, {'node': {'id': 379, 'title': 'Heppoko Jikken Animation Excel♥Saga', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/2/11744.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/2/11744l.jpg'}}, 'num_recommendations': 1}, {'node': {'id': 31339, 'title': 'Drifters', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/10/80271.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/10/80271l.jpg'}}, 'num_recommendations': 1}]
Anime ID: 39486
Recommendations: []
Anime ID: 11061
Recommendations: [{'node': {'id': 5114, 'title': 'Fullmetal Alchemist: Brotherhood', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1208/94745.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1208/94745l.jpg'}}, 'num_recommendations': 75}, {'node': {'id': 21, 'title': 'One Piece', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1244/138851.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1244/138851l.jpg'}}, 'num_recommendations': 61}, {'node': {'id': 392, 'title': 'Yuu☆Yuu☆Hakusho', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1228/111372.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1228/111372l.jpg'}}, 'num_recommendations': 59}, {'node': {'id': 20, 'title': 'Naruto', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1141/142503.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1141/142503l.jpg'}}, 'num_recommendations': 45}, {'node': {'id': 34599, 'title': 'Made in Abyss', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/6/86733.webp', 'large': 'https://cdn.myanimelist.net/images/anime/6/86733l.webp'}}, 'num_recommendations': 28}, {'node': {'id': 31964, 'title': 'Boku no Hero Academia', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/10/78745.webp', 'large': 'https://cdn.myanimelist.net/images/anime/10/78745l.webp'}}, 'num_recommendations': 26}, {'node': {'id': 40221, 'title': 'Kami no Tou', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1702/106229.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1702/106229l.jpg'}}, 'num_recommendations': 26}, {'node': {'id': 14719, 'title': 'JoJo no Kimyou na Bouken (TV)', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/3/40409.webp', 'large': 'https://cdn.myanimelist.net/images/anime/3/40409l.webp'}}, 'num_recommendations': 21}, {'node': {'id': 14513, 'title': 'Magi: The Labyrinth of Magic', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/11/42773.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/11/42773l.jpg'}}, 'num_recommendations': 19}, {'node': {'id': 20899, 'title': 'JoJo no Kimyou na Bouken Part 3: Stardust Crusaders', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/11/55267.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/11/55267l.jpg'}}, 'num_recommendations': 16}]
Anime ID: 9969
Recommendations: [{'node': {'id': 9863, 'title': 'SKET Dance', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/9/73974.webp', 'large': 'https://cdn.myanimelist.net/images/anime/9/73974l.webp'}}, 'num_recommendations': 5}, {'node': {'id': 11843, 'title': 'Danshi Koukousei no Nichijou', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/3/33257.webp', 'large': 'https://cdn.myanimelist.net/images/anime/3/33257l.webp'}}, 'num_recommendations': 4}, {'node': {'id': 2026, 'title': 'Hayate no Gotoku!', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/7/73932.webp', 'large': 'https://cdn.myanimelist.net/images/anime/7/73932l.webp'}}, 'num_recommendations': 1}, {'node': {'id': 4192, 'title': 'Hayate no Gotoku!!', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1015/142749.webp', 'large': 'https://cdn.myanimelist.net/images/anime/1015/142749l.webp'}}, 'num_recommendations': 1}, {'node': {'id': 9513, 'title': 'Beelzebub', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/3/28013.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/3/28013l.jpg'}}, 'num_recommendations': 1}, {'node': {'id': 114, 'title': 'Sakigake!! Cromartie Koukou', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1782/130913.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1782/130913l.jpg'}}, 'num_recommendations': 1}, {'node': {'id': 24, 'title': 'School Rumble', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1465/142014.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1465/142014l.jpg'}}, 'num_recommendations': 1}, {'node': {'id': 16211, 'title': 'Bakumatsu Gijinden Roman', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/9/43673.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/9/43673l.jpg'}}, 'num_recommendations': 1}, {'node': {'id': 13535, 'title': 'Binbougami ga!', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/8/39333.webp', 'large': 'https://cdn.myanimelist.net/images/anime/8/39333l.webp'}}, 'num_recommendations': 1}, {'node': {'id': 19815, 'title': 'No Game No Life', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1074/111944.webp', 'large': 'https://cdn.myanimelist.net/images/anime/1074/111944l.webp'}}, 'num_recommendations': 1}]
Anime ID: 15417
Recommendations: [{'node': {'id': 14765, 'title': 'Ixion Saga DT', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/8/42863.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/8/42863l.jpg'}}, 'num_recommendations': 2}, {'node': {'id': 11843, 'title': 'Danshi Koukousei no Nichijou', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/3/33257.webp', 'large': 'https://cdn.myanimelist.net/images/anime/3/33257l.webp'}}, 'num_recommendations': 1}, {'node': {'id': 114, 'title': 'Sakigake!! Cromartie Koukou', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/1782/130913.jpg', 'large': 'https://cdn.myanimelist.net/images/anime/1782/130913l.jpg'}}, 'num_recommendations': 1}, {'node': {'id': 9863, 'title': 'SKET Dance', 'main_picture': {'medium': 'https://cdn.myanimelist.net/images/anime/9/73974.webp', 'large': 'https://cdn.myanimelist.net/images/anime/9/73974l.webp'}}, 'num_recommendations': 1}]
Anime ID: 820

In [10]:
anime_df2 = pd.read_csv('missing_ids.csv')

In [11]:
anime_df2.head()

   anime_ids
0      10261
1      10378
2      10620
3       1079
4      11859

In [13]:
recommendations2 = anime_manager.get_anime_recommendations(list(anime_df2['anime_ids']), use_mal=True)

Retrieving recommendations for 249 anime from MAL API...

Fetching recommendations from MAL API:  60%|██████    | 150/249 [02:06<01:13,  1.35it/s]

Error retrieving recommendations for anime 39534: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/39534?fields=recommendations

Fetching recommendations from MAL API:  61%|██████    | 151/249 [03:36<45:16, 27.72s/it]

Error retrieving recommendations for anime 39605: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/39605?fields=recommendations

Fetching recommendations from MAL API:  61%|██████    | 152/249 [05:07<1:15:19, 46.59s/it]

Error retrieving recommendations for anime 39783: 504 Server Error: Gateway Timeout for url: https://api.myanimelist.net/v2/anime/39783?fields=recommendations

Fetching recommendations from MAL API: 100%|██████████| 249/249 [07:58<00:00,  1.92s/it]

Successfully retrieved recommendations for 249 anime

In [14]:
anime_manager.save_data_to_json(recommendations2, 'anime_recommendations_supplement1.json')

Data saved to anime_recommendations_supplement1.json

'anime_recommendations_supplement1.json'

In [ ]:
G = nx.Graph()
for key, value in recs.items():
    for rec in value:
        G.add_edge(key, rec)